mapme-initiative/mapme.biodiversity

R/get_accessibility.R
Now multiple range values for accessibility can be specified. The function checks for correctness of the values, potentially reduces to only include valid values and issues an error if only misspecified range values have been supplied. URLs for all ranges are the handed to the download routine.
=> added support to download multiple accessibility layers

_pkgdown.yml, vignettes/contributing.Rmd
First version contributers guide. Will merge quickly so that it is available on the documentation website and open a new issue to collect feedback.
=> 26 add a contributers guide

.github/workflows/pkgdown.yaml, DESCRIPTION, NEWS.md, R/get_gmw.R
GMW released a new version 3 under the source url renaming the zip files as well as their content. These changes should support the download and translation to GPKG for the new version.
=> adapted get_gmw to account for v3

DESCRIPTION, NEWS.md, R/get_esalandcover.R, R/get_gfw_emissions.R, R/get_gfw_lossyear.R, R/get_gfw_treecover.R, R/get_nasa_srtm.R
fixes [this](https://github.com/mapme-initiative/mapme.biodiversity/issues/84) issue
=> Improved downloads

NEWS.md, R/utils.R
=> specify crs in make_global_grid

NEWS.md, R/calc_treecover_area_and_emissions.R, R/calc_treecoverloss_emissions.R, tests/testthat/test-calc_treecover_area_and_emissions.R, tests/testthat/test-calc_treecoverloss_emissions.R
Fix emission calculation and include tests
=> fixes #120 emission calculation

R/calc_active_fire_counts.R, R/calc_active_fire_properties.R, man/active_fire_counts.Rd, man/active_fire_properties.Rd, tests/testthat/_snaps/calc_active_fire_properties.md
For NASA firms indicators use only geometry column of portfolio object in `st_intersection()` to avoid repeating portfolio columns
=> fixed error with repeated columns from portfolio object

DESCRIPTION, vignettes/nasa-firms.Rmd
- adds manualWidgets to websites in DESCRIPTION
- load ommited wdpar package in nasa-firms vignette
=> Fix tutorial

.github/workflows/R-CMD-check.yaml, .github/workflows/pkgdown.yaml, .github/workflows/pr-commands.yaml, .github/workflows/test-coverage.yaml
adds v3 for checkout action and enables upload of pkgdown snapshots
=> update r cmd check actions

R/portfolio.R, README.Rmd, README.md, vignettes/output-wide.Rmd
=> fixes related to documentation

NEWS.md, R/register.R
register functions now issue warnings for names already registered.
=> Issue warnings instead of errors for already registered names

_pkgdown.yml
Changes navbar color to make text legible again.
=> change pkgdown color scheme

README.Rmd, README.md
adds note about planned changes to readme
=> add note in readme

README.Rmd, README.md
=> Change readme

R/portfolio.R, man/init_portfolio.Rd
init_portfolio wrongly states that 'MULTIPOLYGON' are supported
=> fix docs init_portfolio

R/calc_indicators.R
Fixes issue with preparing resources for a whole portfolio
=> fixes processing for portfolio based indicators

R/calc_treecover_area.R, R/calc_treecover_area_and_emissions.R, R/calc_treecoverloss_emissions.R, tests/testthat/test-calc_treecover_area.R, tests/testthat/test-calc_treecover_area_and_emissions.R, tests/testthat/test-calc_treecoverloss_emissions.R
=> Auto-detects max year from gfw lossyear (#273)

R/utils.R
=> fixes typo

NEWS.md, R/calc_burned_area.R, R/calc_deforestation_drivers.R, R/calc_drought_indicator.R, R/calc_ecoregion.R, R/calc_elevation.R, R/calc_fatalities.R, R/calc_gsw_change.R, R/calc_gsw_occurrence.R, R/calc_gsw_recurrence.R, R/calc_gsw_seasonality.R, R/calc_gsw_transitions.R, R/calc_landcover.R, R/calc_mangroves_area.R, R/calc_population_count.R, R/calc_precipitation_chirps.R, R/calc_soilproperties.R, R/calc_temperature_min_wc.R, R/calc_traveltime.R, R/calc_treecover_area.R, R/calc_treecover_area_and_emissions.R, R/calc_treecoverloss_emissions.R, R/calc_tri.R
=> datetime as POSIXct

NEWS.md, R/calc_deforestation_drivers.R, tests/testthat/test-calc_deforestation_drivers.R
=> fixes crs transform in calc_deforestation_drivers (#300)

DESCRIPTION, NEWS.md, R/portfolio.R, tests/testthat/test-portfolio.R
=> .check_portfolio now overrides assetid only if non-unique

R/get_nelson_et_al.R, man/nelson_et_al.Rd
=> Update nelson_et_al docs (#308)

NEWS.md, R/get_worldpop.R
=> Uses binary mode for downloading WorldPop if running on Windows

DESCRIPTION, NEWS.md, R/register.R
documentation stated 100,000 ha, but it was actually set to 10,000 ha
=> sets chunk_size to 100,000 ha per default

NEWS.md, R/calc_treecover_area.R, R/calc_treecover_area_and_emissions.R, R/calc_treecoverloss_emissions.R, R/utils.R, tests/testthat/test-utils.R
=> informs about missing landscapemterics pkg

DESCRIPTION, NEWS.md, R/portfolio.R, tests/testthat/test-portfolio.R
=> sets keep_empty to FALSE in write_portfolio

DESCRIPTION, NEWS.md, R/register.R, tests/testthat/test-register.R
Addresses root cause of the issue reported in #335
=> adds probing when outdir is set

NEWS.md, R/get_gfw_emissions.R, R/spatial-utils.R, tests/testthat/test-calc_indicator.R
=> Adjustments to `sf` introducing `POLYGON FULL`

R/get_worldclim.R
This solution aims at fixing the date bracket problem described in the issue #405
=> worldclim data available from 1960 till 2021

DESCRIPTION, NEWS.md, R/get_esalandcover.R, man/esalandcover.Rd, tests/testthat/test-calc_landcover.R
=> Esalandcover
